server:
  port: 8080

spring:
  application:
    name: assistantModerator
  datasource:
    url: jdbc:postgresql://localhost:5433/assistantModerator
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        # Логирование SQL
  thymeleaf:
    cache: false
  jackson:
    deserialization:
      fail-on-unknown-properties: false

# Логирование SQL(Hibernate)
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

# Giga_Chat_2
sber:
  auth:
    url: https://ngw.devices.sberbank.ru:9443/api/v2/oauth
    scope: GIGACHAT_API_PERS
    uid: 019a6281-3e75-7362-9ea7-8bf370c83a6d
    secret: 28e92e50-c3a0-4b7c-8981-158876bbdb39
    rq-uid: 6f0b1291-c7f3-43c6-bb2e-9f3efb2dc98e

