server:
  port: 8081
spring:
  application:
    name: assistantModerator
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        # Логирование SQL
  jackson:
    deserialization:
      fail-on-unknown-properties: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    clear-checksums: true
# Giga_Chat_2
sber:
  auth:
    url: https://ngw.devices.sberbank.ru:9443/api/v2/oauth
    scope: GIGACHAT_API_PERS
    uid: ${GIGACHAT_UID}
    secret: ${GIGACHAT_SECRET}
    rq-uid: ${GIGACHAT_RQ_UID}
jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}